name: Release

# 触发条件: 这里是push以”v“开头的tag触发
on:
  push:
    # 根据branch或者tags来触发
    branches:
      - canary
  workflow_dispatch: 

    tags:
      - "v*"
    # 忽略的标签类型，不触发构建流程(和tags不能同时写)
    # tags-ignore:
    #   - "d*"

# strategy:
  # 矩阵使用: ${{ matrix.os }}
  # 下面两个矩阵，会代码就会执行 2 * 3 = 6次
  # matrix:
  #  os: [ubuntu-16.04, ubuntu-18.04]
  #  node: [6, 8, 10]

# 一次持续集成的运行，可以完成多个任务(下面就build)
jobs:
  builds:
    # 构建的系统(ubuntu、windows、macos)
    runs-on: ubuntu-latest

    # 可以依赖其他job
    # needs: xxxJob、[job1, job2]

    # 构建权限，ncipollo/release-action需要使用
    permissions:
      contents: write

    # 操作步骤(按顺序执行)
    steps:

      # 拉取仓库代码
      - uses: actions/checkout@v3

      # 设置Java运行环境(temurin是开源jdk)，可以设置为: 1.8
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 设置gradle环境(比如: 6.5)、打包命令
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.13
          
      - name: Permission
        run: chmod +x ./gradlew
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
 
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
         name: app-debug
         path: app/build/outputs/apk/debug/app-debug.apk
